### GET all
GET http://localhost:8000/api/monarchs?firstName=karl

### GET all monarchs (default page=1, pageSize=10)
GET http://localhost:8000/api/monarchs?house=Vasa&page=1&pageSize=5

### GET all search
GET http://localhost:8000/api/monarchs?s=1496

### GET one
GET http://localhost:8000/api/monarchs/2

### GET all filtered
GET http://localhost:8000/api/monarchs?regnalName=karl-xiv-johan

### GET Path param
GET http://localhost:8000/api/monarchs/filter/birthYear/1496

### POST create
POST http://localhost:8000/api/monarchs
Content-Type: application/json

{
  "birthName": "Gustav Adolf",
  "regnalName": "Gustav II Adolf",
  "firstName": "Gustav",
  "regnal": "II",
  "house": "Vasa",
  "birthYear": 1594,
  "deathYear": 1632,
  "reignStart": 1611,
  "reignEnd": 1632,
  "birthPlace": "Stockholm, Sweden",
  "religion": "Lutheran",
  "burialPlace": "Riddarholm Church, Stockholm, Sweden",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/22/Attributed_to_Jacob_Hoefnagel_-_Gustavus_Adolphus%2C_King_of_Sweden_1611-1632_-_Google_Art_Project.jpg",
  "bio": "Gustav II Adolf, known as the Lion of the North, was a brilliant military commander and king of Sweden who led the nation to major victories during the Thirty Years' War."
}

### PUT update by ID
PUT http://localhost:8000/api/monarchs/6
Content-Type: application/json

{
  "firstName": "Guffezz"
}

### DELETE by ID
DELETE http://localhost:8000/api/monarchs/14

### Not Found
GET http://localhost:8000/api22
