### GET all
GET http://localhost:8000/api/monarchs

### GET all search
GET http://localhost:8000/api/monarchs/search?birthName=gustav-eriksson

### GET one
GET http://localhost:8000/api/monarchs/2

### GET all filtered
GET http://localhost:8000/api/monarchs?house=vasa

### GET Path param
GET http://localhost:8000/api/monarchs/filter/birthYear/1594

### POST create
POST http://localhost:8000/api/monarchs
Content-Type: application/json

{
  "birthName": "Gustav Adolf",
  "regnalName": "Gustav II Adolf",
  "firstName": "Gustav",
  "regnal": "II",
  "house": "Vasa",
  "birthYear": 1594,
  "deathYear": 1632,
  "reignStart": 1611,
  "reignEnd": 1632,
  "birthPlace": "Stockholm, Sweden",
  "religion": "Lutheran",
  "burialPlace": "Riddarholm Church, Stockholm, Sweden",
  "imageUrl": "/images/image-placeholder.jpeg",
  "bio": "Gustav II Adolf, known as the Lion of the North, was a brilliant military commander and king of Sweden who led the nation to major victories during the Thirty Years' War."
}

### PUT update by ID
PUT http://localhost:8000/api/monarchs/6
Content-Type: application/json

{
  "firstName": "Guffezz"
}

### DELETE by ID
DELETE http://localhost:8000/api/monarchs/12

### Not Found
GET http://localhost:8000/api/monarchs/search?house=henry